import React from 'react';
import Layout from "../../components/Layout";
import Head from "next/head";
import Header from "../../components/Header";
import Card from "../../components/Card";
import Typo from "../../components/Typo";
import Input from "../../components/Input";
import Form from "../../components/form/Form";
import {useForm} from "react-hook-form";
import FormControl from "../../components/form/FormControl";
import Button from "../../components/Button";

const SearchAddressPage = () => {
  const form = useForm({
    mode: 'onBlur',
    defaultValues: {
      'address': ''
    }
  })

  return (
    <Layout>
      <Head>
        <title>Search Address | Cryptolice</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Header/>

      <main
        className={'flex flex-col justify-center items-center mt-32'}
      >
        <Card className={'w-[600px] !py-12 !px-12'}>
          <Typo.Title className={
            '!text-4xl'
          }>
            Search Address
          </Typo.Title>
          <Typo.Normal className={'mt-1'}>
            Type-in the address of smart contract to check its security
          </Typo.Normal>

          <div className={'mt-8'}>
            <Form
              form={form}
              onSubmit={(data) => {
                console.log('submit', data);
              }}>
              <div className={'flex items-center'}>
                <FormControl name={'address'} className={'flex-1'}>
                  <Input
                    placeholder={'address of smart contract, e.g. 0x0000000000000'}
                  />
                </FormControl>

                <Button
                  type={'submit'}
                  state={'primary'}
                  className={'!w-[120px] ml-4'}>
                  Search
                </Button>
              </div>
            </Form>
          </div>

        </Card>

      </main>
    </Layout>
  );
};

export default SearchAddressPage;