import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Typo from '../components/Typo';
import Button from "../components/Button";

const Home: NextPage = () => {
  return (
    <div className={'max-h-full overflow-y-scroll px-12 pt-4'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Header/>

      <main>
        <div className={'w-full py-24 flex flex-col justify-center items-center'}>
          <Typo.Title className={'!text-6xl'}>
            CRYPTOLICE
          </Typo.Title>

          <Typo.Normal className={'!text-3xl text-center mt-4'}>
            Eliminate the risk of getting scammed before doing transactions in web3
          </Typo.Normal>

          <div className={'flex justify-center items-center w-[400px] mt-32'}>
            <Button state={'primary'}>Search Address</Button>
            <Button className={'ml-4'}>Report Address</Button>
          </div>

          <Typo.Normal className={'!text-lg !text-slate-500 hover:border-b-2 cursor-pointer mt-8'}>
            DOWNLOAD OUR EXTENSION
          </Typo.Normal>
        </div>
      </main>
    </div>
  )
}

export default Home
